# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 972a05d6b3a30ec433659ef472217f76898510ca03f81a9b332e107af4be61db819dd46b783ae2a2fcdca23684d6ff92feb59e3da4a845679e8db644f86e42e0

test:
  secret_key_base: facab56383d9efe38dca70c60bc8f643cbde5ea81ae794a8ecfab05b8259c5be026c268d1b30f0adb1388ca3ef1dc05ed64024641139e5ae685b56915827b112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
